#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

which rvm >/dev/null 2>&1 && {
  echo "Sorry, $0 can not be used with rvm."
  exit 1
}

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  brew bundle check >/dev/null 2>&1  || {
    echo "==> Installing Homebrew dependencies…"
    brew bundle
  }
elif [ "$(uname -s)" = "Linux" ] && [ -f "/etc/debian_version" ]; then

  # Install rbenv if needed
  which rbenv >/dev/null 2>&1  || {
    echo "==> Installing Dependencie -- rbenv"
    sudo apt-get update && sudo apt-get install -y autoconf bison build-essential \
      libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm3 libgdbm-dev
    git clone https://github.com/rbenv/rbenv.git ~/.rbenv
    cd ~/.rbenv && src/configure && make -C src
    grep 'export PATH="$HOME/.rbenv/bin:$PATH"' ~/.bashrc > /dev/null 2>&1 || {
      echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
    }
    grep 'eval "$(rbenv init -)"' ~/.bashrc > /dev/null 2>&1 || {
      echo 'eval "$(rbenv init -)"' >> ~/.bashrc
    }
    export PATH="$HOME/.rbenv/bin:$PATH"
    eval "$(rbenv init -)"
    git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
  }

  # Install docker if needed
  which docker >/dev/null 2>&1  || {
    echo "==> Installing Dependencie -- docker"
    sudo apt-get update && sudo apt-get install docker.io -y
    sudo usermod -aG docker $USER
    newgrp docker
  }

else
  echo "Sorry, only support macOS & Debain system."
  exit 1
fi

if [ -f ".ruby-version" ] && [ -z "$(rbenv version-name 2>/dev/null)" ]; then
  echo "==> Installing Ruby…"
  rbenv install --skip-existing
  which bundle >/dev/null 2>&1  || {
    gem install bundler
    rbenv rehash
  }
fi

if [ -f "Gemfile" ]; then
  echo "==> Installing gem dependencies…"
  bundle check --path vendor/gems >/dev/null 2>&1  || {
    bundle install --path vendor/gems --quiet --without production
  }
fi
