#!/bin/sh

# script/console: Launch a console for the application. Optionally allow an
#                 environment to be passed in to let the script handle the
#                 specific requirements for connecting to a console for that
#                 environment.

set -e

cd "$(dirname "$0")/.."

# no argument provided, so just run the local console in the development
# environment. Ensure the application is setup first.
script/setup
bin/console