#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

script/bootstrap


if [ -z "docker images -q zhenkyle/docker-sslocal" ]; then
  docker pull zhenkyle/docker-sslocal
fi

if [ -z "docker images -q zhenkyle/shadowsocksr" ]; then
  docker pull zhenkyle/shadowsocksr
fi

echo "==> App is now ready to go!"